-- 0016: support tickets from the site chat widget.
-- Forward-only, idempotent (create table if not exists).
-- Ticket numbers start at #101 so early tickets don't look like "#1".

create table if not exists public.support_tickets (
  id bigint generated by default as identity (start with 101) primary key,
  name text,
  email text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.support_tickets enable row level security;

-- Service-role access only — no anon/authenticated policies.
